In [1]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Problem 1: Matrix product is calculated manually

First lets get to know our MatrixA & MatrixB:

$$ Matrix A $$

$$
\begin{bmatrix}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & -9
\end{bmatrix}
$$


$$Matrix B$$

$$
\begin{bmatrix}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1
\end{bmatrix}
$$


By hand, the multiplicayion of Matrixes follows the following process:

$$
\begin{bmatrix} -1 & 2 & 3 \\ 4 & -5 & 6 \\ 7 & 8 & -9 \end{bmatrix}
\quad \text{x} \quad
\begin{bmatrix} 0 & 2 & 1 \\ 0 & 2 & -8 \\ 2 & 9 & -1 \end{bmatrix}
\quad \text{=} \quad
\begin{bmatrix} (-1)*0 + 2*0 + 3*2 & (-1)*2+2*2+3*9 & (-1)*1 + 2*(-8) + 3*(-1) \\ 4*0 + (-5)*0 + 6*2 & 4*2 + (-5)*2 + 6*9 & 4*1 + (-5)*(-8) + 6*(-1) \\ 7*0 + 8*0 + (-9)*2 & 7*2 + 8*2 + (-9)*9 &  7*1 + 8*(-8) + (-9)*(-1) \end{bmatrix}
$$


_______________________________________________________________________________________________________________________________
**The result of that multiplication will be:**

$$
Matrix A * Matrix B = \begin{bmatrix}
6 & 29 & -20 \\
12 & 52 & 38 \\
-18 & -51 & -48
\end{bmatrix}
$$


# Problem 2: Calculation by NumPy function

In [7]:
result = np.dot(a_ndarray, b_ndarray)
result

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# Problem 3: Implementation of calculation of a certain element

In [17]:
c0_0 = 0

for k in range (3):
    A = a_ndarray[0,k]
    B = b_ndarray[k,0]
        
    c0_0 += A*B
    print(f"k={k}:  A[0,{k}] * B[{k},0]  =  {A} * {B}  =  {A * B}")

k=0:  A[0,0] * B[0,0]  =  -1 * 0  =  0
k=1:  A[0,1] * B[1,0]  =  2 * 0  =  0
k=2:  A[0,2] * B[2,0]  =  3 * 2  =  6


# Problem 4: Creating a function that performs matrix multiplication

In [29]:
c3_3 = 0

for i in range (3):
    for j in range (3):
        A = a_ndarray[i,j]
        B = b_ndarray[j,i]
        c3_3 += A*B
        
        print(f"i,j={i},{j}:  A[{i},{j}] * B[{j},{i}]  =  {A} * {B}  =  {A * B}")
    print("")
    

i,j=0,0:  A[0,0] * B[0,0]  =  -1 * 0  =  0
i,j=0,1:  A[0,1] * B[1,0]  =  2 * 0  =  0
i,j=0,2:  A[0,2] * B[2,0]  =  3 * 2  =  6

i,j=1,0:  A[1,0] * B[0,1]  =  4 * 2  =  8
i,j=1,1:  A[1,1] * B[1,1]  =  -5 * 2  =  -10
i,j=1,2:  A[1,2] * B[2,1]  =  6 * 9  =  54

i,j=2,0:  A[2,0] * B[0,2]  =  7 * 1  =  7
i,j=2,1:  A[2,1] * B[1,2]  =  8 * -8  =  -64
i,j=2,2:  A[2,2] * B[2,2]  =  -9 * -1  =  9



# Problem 5:

In [51]:
def matrix_multiply_safe(matrix_a, matrix_b):
    row_a = len(matrix_a)
    cols_a = len(matrix_a[0])

    row_b = len(matrix_b)
    column_b = len(matrix_b[0])
    
    
    if cols_a != row_b:
        print(f"This matrix multiplication cannot be done, because the matrix shape of {matrix_a.shape} is not compatible with the second matrix {matrix_b.shape}")
        return None

    result_mtx = 0
    for i in range (row_a):
        for j in range (row_a):
            A = matrix_a[i,j]
            B = matrix_b[j,i]
            result_mtx += A*B
            print(f"i,j={i},{j}:  A[{i},{j}] * B[{j},{i}]  =  {A} * {B}  =  {A * B}")
    print("")
    return result_mtx



In [52]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

check = matrix_multiply_safe(d_ndarray, e_ndarray)
check

This matrix multiplication cannot be done, because the matrix shape of (2, 3) is not compatible with the second matrix (2, 3)


In [53]:
check1 = matrix_multiply_safe(a_ndarray, b_ndarray)
check1

i,j=0,0:  A[0,0] * B[0,0]  =  -1 * 0  =  0
i,j=0,1:  A[0,1] * B[1,0]  =  2 * 0  =  0
i,j=0,2:  A[0,2] * B[2,0]  =  3 * 2  =  6
i,j=1,0:  A[1,0] * B[0,1]  =  4 * 2  =  8
i,j=1,1:  A[1,1] * B[1,1]  =  -5 * 2  =  -10
i,j=1,2:  A[1,2] * B[2,1]  =  6 * 9  =  54
i,j=2,0:  A[2,0] * B[0,2]  =  7 * 1  =  7
i,j=2,1:  A[2,1] * B[1,2]  =  8 * -8  =  -64
i,j=2,2:  A[2,2] * B[2,2]  =  -9 * -1  =  9



10

# Problem 6: Transposition

In [54]:
a_ndarray

array([[-1,  2,  3],
       [ 4, -5,  6],
       [ 7,  8, -9]])

In [55]:
a_T = a_ndarray.T
a_T

array([[-1,  4,  7],
       [ 2, -5,  8],
       [ 3,  6, -9]])